#!/bin/bash

# http://stackoverflow.com/a/246128/656878
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

if [ -z "$1" ]
then
	echo "Missing SolrQuery argument"
	exit 1
fi

"$DIR/kowalski-jms-broker/bin/artemis-service" start
sleep 20
"$DIR/kowalski/bin/kowalski-service" start "$1" input
sleep 10
"$DIR/kowalski-call-graph/bin/kowalski-call-graph-service" start
